version: '1'
services:
  discordbot:
    container_name: botDiscord
    build: .
    env_file:
      - .env
  mongodb:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./data:/data/db
